### ISSUE TITLE
Words

### ISSUE THREAD

**Issue by Blackfish95** [teslamotors/light-show#1]
Question: can you create other words with the headlights? The default holiday light show spells out TESLA. Didn't see anything in your docs about spelling other words. Thx!

**Comment by anatolinicolae** [comment]
Perhaps Text elements can be used, but yeah I would appreciate some docs in regards.

**Comment by SvemerRobin** [comment]
I have tried using text elements but it still displya tesla whatever the text I put in. Can someone say if they succeded in changing the text in the high beams?

**Comment by MrPaulAR** [comment]
There is only 1 channel available in any of the effects.  That 1 channel has 255 (8 bits) available to it for a brightness.  Tesla engineers have done some custom logic around many of these effects (25% brightness to open for example) but most lights are either ON or OFF.

This is not exposed to xLights as a matrix [today] so it's currently not possible.

**Comment by MattJeanes** [comment]
Yeah I'm assuming that the TESLA projection is always shown with any fseq or there's some custom magic with the built in one. My car doesn't have the projector but it would be awesome if this had support to modify the matrix projection, you could make some really neat effects with that.
