### ISSUE TITLE
Custom USB shows disappear on M3 Highland 

### ISSUE THREAD

**Issue by eried** [teslamotors/light-show#109]
I have tried with multiple usb drives (multiple/single partitions, fat32 vs exfat) and I think there is an issue on the latest m3 highland software that makes the custom shows disappear.

It always work after rebooting the car, waiting 30-40 seconds, custom lightshows appear, boombox custom horns and everything is fine. After a while, the custom lightshows disappear but the boombox and tesladrive are  fine.

Anyone else here with this issue?

**Comment by danfratamico** [comment]
I just tried to load multiple light shows on a partitioned drive, labeling each as Show1.fseq/Show1.mp3, Show2.fseq/Show2.mp3, etc. but the custom light show is greyed out. If I put one light show on the USB and label it as lightshow.fseq and lightshow.wav, it works. I'm on 2024.32.7.

**Comment by eried** [comment]
> I just tried to load multiple light shows on a partitioned drive, labeling each as Show1.fseq/Show1.mp3, Show2.fseq/Show2.mp3, etc. but the custom light show button is greyed out. If I put one light show on the USB and label it as lightshow.fseq and lightshow.wav, it works. I'm on 2024.32.7.

Hey, thanks I will try with a single show. I'm pretty sure I tried renaming to that name in my tests but I had a .mp3

**Comment by eried** [comment]
@danfratamico I just tried with an empty usb only with the LightShow folder and lightshow.fseq/lightshow.wav files and does not work, for me it only works for a while after a reboot. Reboot -> wait 30 secs -> custom lightshows appear OK. Boombox and tesladrive that is on the same drive always work OK, it is only the custom lightshows not appearing 😐

**Comment by eried** [comment]
I think this is a bug all model 3 highland (it is ok since this functionality is very low priority, but strange either way)

https://teslamotorsclub.com/tmc/posts/8467202/
https://www.reddit.com/r/TeslaLightShow/comments/1g6f21l/comment/lsj412y/?context=3

**Comment by eried** [comment]
> Tried another flash disk (formatted on Tesla), tried to reboot, and also tried to have 1 song (2 files)…. not working….

For what I have observed is, 

1. remove the flash disk 
2. reboot car holding the two knobs down 
3. wait 30 seconds and connect it again

it will work until few reboots (if boombox and teslacam are in the same flash disk, on other partitions, they will be ok, it is just the lightshows)

**Comment by denis-rafailov** [comment]
> > Tried another flash disk (formatted on Tesla), tried to reboot, and also tried to have 1 song (2 files)…. not working….
> 
> For what I have observed is,
> 
> 1. remove the flash disk
> 2. reboot car holding the two knobs down
> 3. wait 30 seconds and connect it again
> 
> it will work until few more rides, maybe unlocking/locking the car is messing the loading of shows? (if boombox and teslacam are in the same flash disk, on other partitions, they will be ok, it is just the lightshows)

Can I simulate the falure without a car? I am looking for a ticket that could make my hands dirty without a car
.

**Comment by jaimevisser** [comment]
Seems this has been fixed in the Christmas update.

**Comment by eried** [comment]
Yes
