### ISSUE TITLE
Channels: dome lights, reading lights, horn

### ISSUE THREAD

**Issue by dtkachev** [teslamotors/light-show#12]
Add additional channels, if technically possible and appropriate:
- Driver dome light
- Passenger dome light
- Rear passenger right light
- Rear passenger left light
- Horn (not a light, but a cool use case...)

**Comment by JVB-Tesla** [comment]
Interesting suggestion.

**Comment by dtkachev** [comment]
- Megaphone (not a light, but a cool use case https://twitter.com/Tesla/status/1478763378319544329?s=20)
