### ISSUE TITLE
FEAT:  Add additional validation to validator.py that provides command count

### ISSUE THREAD

**Issue by cantechit** [teslamotors/light-show#18]
Feature Req:  The existing validator.py doesn't provide enough granular information about why light-show output files from xLights are too large, the Memory % value seems to wildly fluctuate higher even when commands are removed

**Comment by bendudz** [comment]
The validation results give a frame count if the FSEQ is valid. The [documentation](https://github.com/teslamotors/light-show#general-limitations-of-custom-shows) states max command count (transition of light / closure state ie on -> off / open -> closed) is 681 but bear in mind, commands that start at the same timestamp counts as 1 command.

Memory usage is calculated taking the number of commands & dividing it by 681.

**Comment by bendudz** [comment]
I’ve revisited your comments & now include total commands used #20

**Comment by entendu** [comment]
+1, was looking for this

**Comment by JVB-Tesla** [comment]
Good suggestion. We'll make this change.

**Comment by entendu** [comment]
@JVB-Tesla see pr #20
