### ISSUE TITLE
Documentation not suitable for MacOS

### ISSUE THREAD

**Issue by fatbasstard** [teslamotors/light-show#2]
Hi, great initiative to open this up to the world! 

Just quickly tried it out on my Mac and the documentation is not totally compatible with the MacOS setup, mainly because the xLights application is different than the version used in the documentation.

Would be nice to put som "mac specific" documentation here and there.

**Comment by JVB-Tesla** [comment]
Do you have any specific suggestions?

**Comment by kingjamez** [comment]
I had no problems on my M1 MBP running Monterey 12.0.1 The only mac specific thing not mentioned was that preferences is under the "XLIGHTS" menu not "File", but anyone running MacOS would figure this out.

**Comment by wzr1337** [comment]
No issues on mac.. just look for preferences under `xLights` at the very top left of your screen, as @kingjamez  suggests

**Comment by fatbasstard** [comment]
Well, it indeed started with the `file` thing (not that shocking, but also hit the '3D' option missing.... It was late and was on my laptop only (small screen) so whn I was not seeing any decent car image so stopped there for now.

Good to see that it apparently is the only thing that was off, just wanted to give an early heads up...  

I'll also play around on Windows and will create PR's if I got any improvements 👍
