### ISSUE TITLE
FEAT: Parade mode

### ISSUE THREAD

**Issue by davidwkeith** [teslamotors/light-show#23]
I understand why drivers shouldn't be able to start a show while the car is moving, but if we latched onto valet mode, a parade mode could be created. Rules might look like:

- Car must be in park to enable parade mode
- Car can't go over 10MPH (or whatever the top safe speed is for a parade)
- Driver must keep hands on wheel
- Parade mode loops whatever animation is loaded until stopped
- Giant stop/resume buttons on screen when playing
- Extra aggressive collision detection (really just this alone would be cool for many float tow vehicles)
- Doors, trunks, and other physical safety device animations are ignored
  
Optional things that would take more engineering

- External lights support
- External sound system support
- External controller support
- Self driving parade mode (one can dream)

**Comment by JVB-Tesla** [comment]
Thanks for the suggestion. There are regulations that require the lights to operate in specific ways while driving.
