### ISSUE TITLE
FEAT: Musical Horn

### ISSUE THREAD

**Issue by davidwkeith** [teslamotors/light-show#24]
Hi, I just arrived from the '80s and found this repo. Not sure what git it, but it looks cool.

My grandfather had a musical horn on his black Ford F-150. Unfortunately it played songs like Dixie Land as he drove us to the dump to go shopping for bikes. But it was fun.

Using the external speaker is great, but flashing some lights and playing a song as the car pulls up would be cool for many scenarios:

- **Car Share:** Uber says a Tesla will be arriving playing the driver's theme song
- **Deliveries:** Dinner arrives playing the restaurant's theme song
- **Visiting Family:** This is me, I would pull up playing some funny song
- **Going to the dump with your grandfather:** I mean the town has curbside collection, and he still drives to the dump every week. Might as well have some fun with the stinky load in the back.

Probably many other events would warrant this. Basically allow a stripped down show on demand when driving. Ideally trigger it based on GPS directions to happen on arrival.

**Comment by JVB-Tesla** [comment]
Thanks for the suggestion. There are regulations that require the lights to operate in specific ways while driving.
