### ISSUE TITLE
Keygen cyberpunk music the music fits perfectly

### ISSUE THREAD

**Issue by peterwillcn** [teslamotors/light-show#25]
Keygen cyberpunk music the music fits perfectly
http://www.keygenmusic.net/?page=team&teamname=zwt&lang=en
https://www.bilibili.com/video/av21000000

**Comment by josephzhang12** [comment]
我以为你编好了呢

**Comment by JVB-Tesla** [comment]
Nice suggestion!

Looking forward to seeing what you do with it :-)
https://github.com/teslamotors/light-show

Or float the suggestion to https://www.reddit.com/r/TeslaLightShow/
