### ISSUE TITLE
When can we customize LED projector headlamps

### ISSUE THREAD

**Issue by lm339** [teslamotors/light-show#28]
When can we customize LED projector headlamps

**Comment by anatolinicolae** [comment]
Duplicate of #1 perhaps?

**Comment by JVB-Tesla** [comment]
>> When can we customize LED projector headlamps

Agree this would be awesome. Significant engineering required to make this happen ... join us!

https://www.tesla.com/careers/search/

Software Validation Engineer, Body Controls
System Integration Engineer, Body Controls
System Validation Engineer, Body Controls
Embedded Software Engineer, Body Controls

**Comment by vish1** [comment]
Any progress on this feature?
