### ISSUE TITLE
Update the instructions.

### ISSUE THREAD

**Issue by beaudamore** [teslamotors/light-show#29]
There are several steps missing from the setup instructions including unzipping zips inside the main zip, sourcing the project down into those actual unzipped/unzipped files before finding the models... that took time and was confusing and still doesn't explain how to use it.
Try following your own instructions, see how far you get.

**Comment by jalexy12** [comment]
Open a PR!

**Comment by jdandrea** [comment]
What jalexy12 said. Try being kinder in your issue filing.

**Comment by beaudamore** [comment]
My bad. Not meant to offend. Texting cannot confer voice inflections. Being originally from NJ, it’s how we “talk”. Simple blunt. 
I’m not big on Linux, maybe it’s all me. 
The only model I can find is the S. 
I’m stuck at that point and, seriously, following the directions doesn’t make it work for me but, like I said, maybe it’s me. Frustrated. Again, my apologies.

**Comment by jalexy12** [comment]
Yeah I’m from the north too — not a great excuse for bad communication and poor attitude. 

It specifically says in the instructions the S model is a fill in and has all lights that all models have. It’s the only model.
