### ISSUE TITLE
Update ramping lights documentation

### ISSUE THREAD

**Issue by Nexuist** [teslamotors/light-show#30]
As a shortcut I tried using ramping down effects only to make a light show and not a single light turned on. Turns out the ramping effects don't actually do anything if the light isn't already on or off before the ramping effect is entered. Update the ramping effect notes to make this clear so that the next unfortunate soul to try this doesn't have to sit there adjusting brightness and durations manually :P

**Comment by SpaceRagnar** [comment]
Its make sense - you can not turn off your light if its did not turn on! Also you need to remember - your "turn on" timestamp and "ramping down" timestamp MUST tuch each other! Other way for programm it will be = "turn on" -> "turn off" -> "ramping down" ;-)

**Comment by JVB-Tesla** [comment]
We'll consider clarifications to the documentation. Thanks for highlighting.
