### ISSUE TITLE
Tesla Model 3 Prior to October 2020 - Left/Right Tail function not same

### ISSUE THREAD

**Issue by itsmearvi** [teslamotors/light-show#31]
When the Left Taillight command is issued as mentioned both left and right tail lights were lit (both sections of left tail light and both sections of right tail light).  The same when we give the command for Right Tail Light it lit only trunk portion of left tail light and both trunk and the side portion of the right tail light.  The left portion of the left tail light in the body is not lit.

**Comment by JVB-Tesla** [comment]
Thanks for highlighting. This is fixed and will be addressed in a future Tesla software update.
