### ISSUE TITLE
Adding Model-X to XLights

### ISSUE THREAD

**Issue by SudhindraKovalam** [teslamotors/light-show#33]
Is there a way to add Model X's model to Xlights?

**Comment by m1hah** [comment]
Model X (2021+) is already supported.

If you mean older Model X, there is already an open issue: https://github.com/teslamotors/light-show/issues/5

**Comment by SudhindraKovalam** [comment]
I meant the model to the x_lights project folder. I only see Model_S files in the .zip file in the repo. 
If we want to create a custom show which includes using falcon-wings, we cannot now right?

Don't have a refreshed X (yet!), but would like to get started creating a few sequences

**Comment by cmastudios** [comment]
The channels to control the falcon doors and the power front doors are already included in the project. While the Model S is the only car shown in the preview window, the sequences can run on all car years/models listed in the readme.

**Comment by SudhindraKovalam** [comment]
Wasnt sure if that was doable. Thanks, Will try it out once
