### ISSUE TITLE
Need Help with File Structure - Car not Detecting "Custom Light Show"

### ISSUE THREAD

**Issue by atadistance** [teslamotors/light-show#34]
Sorry for the basic troubleshooting problem, but I've read the ostensibly simple instructions numerous times and am still not able to get my model 3 to detect the custom light show. I suspect it is how I'm downloading/unzipping and saving the xLights and tesla show directory files.  

FWIW, I'm able to operate the xlights program and create sequences just fine, but when I save the sequence, my LightShow folder has numerous subfolders in addition to the FSEQ file, including an xLights Program file (which I thought would have been my .MP3 file), backup file, etc., which I suspect is wrong.

A few questions:

After download, do i install the xlights application within LightShow folder, or can that be anywhere on my disk drive? Do I unzip and install the tesla show folder in the LightShow folder?

Do the LightShow files have to literally be named lightshow.fseq and lightshow.mp3?

Do I have to manually move my .mp3 file into the LightShow folder, or should that happen automatically when I "Save Sequence As" into LightShow folder? I assume it should be the latter, but when I save the sequence it never includes a .mp3 file., only a second file with an xLights icon called an "xLights Program file."

I can post screenshots this evening if it'll help. 

Thanks.

**Comment by xsorifc28** [comment]
This section should answer some of your questions: 
https://github.com/teslamotors/light-show#usb-flash-drive-requirements

Also, make sure that you validate the lightshow.fseq file.

**Comment by SpaceRagnar** [comment]
Your USB and your work with project should be separeted complitely!
Do everything you need using only your computer's space. Then insert USB, format it in FAT32, craet "LightShow" folder, put 2 files in that folder. Nothing else!

**Comment by romerica** [comment]
@atadistance make sure you rename the .fseq  and .mp3 or .wav files as lightshow.fseq, lightshow.mp3, lightshow.wav

...that solved my issues......working flawlessly....

**Comment by stefaanbolle** [comment]
Not working with me neither. M3LR 2021.
Tried already 3 USB sticks (formatted with a Mac and Win 10 and Win 11 system)
When starting the lightshow, it is always the built-in one.
No clue why it does not detect the custom sequence

**Comment by atadistance** [comment]
Thanks for your responses everyone. I will keep the files separate and rename the final files accordingly.

**Comment by RubytheTesla** [comment]
If you have a 2022 Model 3/Y the USB-C ports are power only.  You will need to use the USB port in the glovebox where the drive for camera recording is located.

**Comment by atadistance** [comment]
So.......tried again, failed again. No idea why. Using a FAT32 formatted USB (actually tried 2 different sticks), following all of the required naming/file protocols, and nothing. My 2018 M3LR recognizes the USB, and the music app reads and plays the .mp3 file. 

Here's a screenshot of my USB drive in the file explorer. Do these files otherwise look like they're supposed to look (FSEQ file has a blank sheet icon and is 272kb)? Any other ideas?

![LigthShow File Explorer](https://user-images.githubusercontent.com/96835779/148241155-1364ddb5-24af-4693-8233-c845803057fe.jpg)

Normally I wouldn't care and would be done with this, but trying to surprise the wife for our anniversary, so any help is appreciated....

**Comment by JVB-Tesla** [comment]
@atadistance , suggest you post on https://www.reddit.com/r/teslalightshow if additional debug is required.

**Comment by cmastudios** [comment]
> My 2018 M3LR recognizes the USB, and the music app reads and plays the .mp3 file.

The music app on the car is able to play the .mp3?

**Comment by atadistance** [comment]
I've posted to the tesla light show subreddit, but just to respond to @cmastudios, yes, the car will play the .mp3 file.

**Comment by Jdice2** [comment]
> stefaanbolle

**Comment by Jdice2** [comment]
> Not working with me neither. M3LR 2021. Tried already 3 USB sticks (formatted with a Mac and Win 10 and Win 11 system) When starting the lightshow, it is always the built-in one. No clue why it does not detect the custom sequence

I am having the same issue on my 2022 Model 3 and I have tried formatting the usb drive several times, and tried this on all usb ports including the one in the glove box.  does anyone have any suggestions?

**Comment by atadistance** [comment]
> > Not working with me neither. M3LR 2021. Tried already 3 USB sticks (formatted with a Mac and Win 10 and Win 11 system) When starting the lightshow, it is always the built-in one. No clue why it does not detect the custom sequence
> 
> I am having the same issue on my 2022 Model 3 and I have tried formatting the usb drive several times, and tried this on all usb ports including the one in the glove box. does anyone have any suggestions?

Just to update, I still haven't gotten it to work on my 2018 M3LR. I've not only validated my own sequence, but other known functional custom shows (like those available for download on repositories) have also not worked. 

Here's my reddit thread on the teslalightshow sub if anyone's interested, as I update progress (lack thereof) on there: https://www.reddit.com/r/TeslaLightShow/comments/rx5yr7/custom_light_show_not_being_detected/

My next step is to try it my flash drive and custom show on someone else's tesla to see if it is something with my car, as opposed to the stick(s), folder/files.

**Comment by RubytheTesla** [comment]
I don't know if this will help but on my 2022 M3LR I have a 4 port unpowered hub plugged into the USB-A port in the Glove Box.  I keep the OEM Dashcam flash drive plugged into the 1st port of the HUB.  When I plug in my LightShow flash drive it is not recognized at all.  Strange as it may seem, if I leave the two drives in the HUB, unplug it, wait until the Dashcam display greys out and plug it back in the car recognizes the Dashcam drive but not the LightShow drive.  However, if I unplug the Dashcam drive from the HUB, wait until the display greys out, then plug it back in (while the LightShow drive in in the HUB) then (magic) the LightShow drive is recognized!

Tesla clearly has a software issue with polling USB ports for a change in status.  This is made worse by deleting the USB data ports elsewhere in the car but not supporting a USB HUB in the only data port available.  How can we, as an Owner's group encourage Tesla to fix this DEBACLE?   The MOST frustrating part is that there is no way to communicate with Tesla.  The sales reps are clueless and have no influence with the development team.

**Comment by atadistance** [comment]
Thanks @RubytheTesla. I'll try anything at this point and while I've tried configurations with dashcam in/out, I haven't tried what worked for you.

**Comment by atadistance** [comment]
> > Not working with me neither. M3LR 2021. Tried already 3 USB sticks (formatted with a Mac and Win 10 and Win 11 system) When starting the lightshow, it is always the built-in one. No clue why it does not detect the custom sequence
> 
> I am having the same issue on my 2022 Model 3 and I have tried formatting the usb drive several times, and tried this on all usb ports including the one in the glove box. does anyone have any suggestions?

Try renaming your .mp3 file just "lightshow", dropping the ".mp3" suffix from your .mp3 file. Apparently some .mp3 files already have the suffix embedded in the file name (my download from amazon music did), and by renaming the file lightshow.mp3, it actually reads lightshow.mp3.mp3, which is wrong.
