### ISSUE TITLE
Unable to load example sequence

### ISSUE THREAD

**Issue by jdandrea** [teslamotors/light-show#38]
Running xLights v2021.40, wxWidgets 3.1.6, macOS 12.0.1. AFAIK all's well with the general setup (FSEQ V2 Uncompressed, etc.).

When I try loading the example `lightshow.xsq` file (not `fseq`), commit 7f9da08, I get:

```
Unable to load sequence: /PATH/TO/light-show/examples/lightshow_example_1/lightshow.fseq
```

Audio never loads either, though I can play it and also load it in to xLights. Moving/copying the sequence folder does not help. File permissions look good, there are no access requests under Security & Privacy in System Preferences, and there's no whitespace in the path, in case that matters. Validation works as well:

```
$ python3 validator.py examples/lightshow_example_1/lightshow.fseq
Found 2247 frames, step time of 20 ms for a total duration of 0:00:44.940000.
Used 16.45% of the available memory
```

Will keep trying to sleuth this out. If anyone has thoughts as to what may be amiss, please share - thank you!

**Comment by JVB-Tesla** [comment]
Suggest you post on https://www.reddit.com/r/teslalightshow if additional support is required. Others have been able to run the example show successfully.
