### ISSUE TITLE
Lets collect nice sequences

### ISSUE THREAD

**Issue by wzr1337** [teslamotors/light-show#4]
Hi all,

let's collect the best of the best sequences.. ;)

https://github.com/wzr1337/tesla-lightshow

**Comment by juanriaza** [comment]
I've set up a community-driven repository here: http://teslalight.show

**Comment by ppttvs** [comment]
> I've set up a community-driven repository here: http://teslalight.show

I'm sorry but why http://teslalight.show refuses/closes my connection? Is it closed or something else?

**Comment by JVB-Tesla** [comment]
We're really excited to see the community response!

https://www.reddit.com/r/teslalightshow

**Comment by Fatso1947** [comment]
I joined the TESLA Lightshow group on Facebook. There are several members -- including myself -- who post light shows and links to the .fseq and .wav files for no charge.  There are others who charge make custom light shows for folks.  I am not crazy about people who charge, but some might find it useful.  To each his own....
