### ISSUE TITLE
Project Directory for Model 3

### ISSUE THREAD

**Issue by hesspoint** [teslamotors/light-show#41]
Hi,
in the instructions it says: Download and unzip tesla_xlights_show_folder.zip, which is the Tesla xLights bare project directory.

I did so but it only contains the Model S. Where can I get the folder for model 3?

thanks

**Comment by adamcoulombe** [comment]
@hesspoint see #23

**Comment by JVB-Tesla** [comment]
Thanks @hesspoint .
