### ISSUE TITLE
Loading lightshow.fseq failled: must be V2 uncompressed

### ISSUE THREAD

**Issue by jmiguels** [teslamotors/light-show#43]
Help!
I am using xLights 2022.01 64bit for windows.
I've prepared a sequence and when insert the USB in my Tesla Model 3 I get this error on the light show: "Loading lightshow.fseq failled: must be V2 uncompressed".
It works good with other shows downloaded from the web.
Any body knows what am I doing wrong?
Thank you in advance!

José Miguel

**Comment by adamcoulombe** [comment]
Did you select v2 uncompressed in your xlights preferences?
![image](https://user-images.githubusercontent.com/469038/148649864-03514556-66c8-41e4-9ebf-32e4b6706ed0.png)

See the readme, this is an important step according to the readme documentation

**Comment by jmiguels** [comment]
Dear Adam,
Thank you for your reply and for your patience. I am very sorry for my stupid question.
I should have played more attention to the instructions.
Best regards
José Miguel Santos

**Comment by adamcoulombe** [comment]
no worries :) You can close this issue if it answers your question.
