### ISSUE TITLE
Show Too Long

### ISSUE THREAD

**Issue by Fatso1947** [teslamotors/light-show#45]
Nothing like a failure to make you learn 🙁
I just completed my first TESLA light show. The show passed all the checks on my laptop, but it would not load in my car -- It said the show was too long.
The instructions on GitHub specify the show cannot be longer than 5 minutes. My show is only 1 minute, 37 seconds.
Since the length of my show is well within the boundaries, the problem must be somewhere else, but I don't know where to look.
Any help and/or suggestions gratefully accepted.

**Comment by kaedenbrinkman** [comment]
Hi there, I believe there is both a time limit (5 minutes) and a number of instructions limit (680 events). You are probably running into the number of instructions limit.

There are some great tips on #17 you should check out.

**Comment by MrPaulAR** [comment]
Please share the output from the validator.  If you cannot figure out how to run the validator.py locally there is an online version @ https://validator.t2k.dev/
