### ISSUE TITLE
Loud bass thump at start of show

### ISSUE THREAD

**Issue by dmarnel** [teslamotors/light-show#46]
There is a very loud bass thump before a show begins. Not sure if this is coming from xLights, or Tesla.  I don’t hear this in any of the videos I’ve seen online.

**Comment by chumeniuk** [comment]
This happens even with the default holiday light show.

**Comment by MrPaulAR** [comment]
Expected behavior.

**Comment by JVB-Tesla** [comment]
Feature, not a bug. This is used to synchronize lights and music.
