### ISSUE TITLE
Light Show For The Legacy Model S and X

### ISSUE THREAD

**Issue by m1hah** [teslamotors/light-show#5]
Hi, not a bug or issue, but a request to enable this feature for the Legacy Model S and X.
2016+ with MCU2 should be able to handle that as well. Model X already has its 1st gen light show.

Thank you!

**Comment by GiannisHaralabopoulos** [comment]
Couldn't care less for light show, but
live sentry feed
Auto heat seat
Dash cam clip management
plus any other feature in m3 or my with Intel atom mcus should work for 'legacy' models.

**Comment by george-valentin** [comment]
Agree, please activate the light show on model s with mcu2 and hw3 < 2021 as well!

**Comment by godvv** [comment]
My model x 2021 pre refresh is legacy, nice

**Comment by Aske1gt** [comment]
Agree, please enable this for 2016/2017+ (facelifted models and beyond with MCU2)

**Comment by CypherGrue** [comment]
If these are cars are "legacy", when will you be releasing the legacy full stack source code for them?

If not, please enable all MCU2 compatible features for 2016/2017+.

**Comment by RGACT56** [comment]
Have a 2019 Raven and I’m surprised how many recent software updates are not available on my car. Can Tesla explain why each are not available and if an upgrade is planned (whether chargeable or not) for these models?

**Comment by carriegong** [comment]
Same would like to add a bump on this. 2020 Raven LR Model S. at least default light show with no customizability would be nice. I know the lights are different with different driver. But at least Model X had this before. would like those same light seq.

**Comment by emulajavi** [comment]
2019 Raven Model S… has the SAME hardware than a 2019 Model3…. So there’s no reason to give the model 3 any exclusivity. 

Please release the Light Show for MCU2 Model S and X, along with Live Sentry and Side Repeaters cameras displayed on the instrument cluster, when using the blinker. 

Thanks.

**Comment by nbmazer08** [comment]
I have a 2020S and would love all the new update items but I guess having a premium car doesn’t mean anything nowadays when less expensive models get priority.

**Comment by echuvyrov** [comment]
I would love to have the ability to program light shows for my Dec 2018 X as well. It doesn't have to be via xLights, but if the API were open and published, we could create our own implementations of light shows against those API.

**Comment by NetFusionDesigns** [comment]
It's messed up Tesla isn't releasing features to their most expensive vehicle, while older cheaper models continue to get updates.

**Comment by PDBNCAF** [comment]
Have a 2020 X please enable light show

**Comment by brewinathome** [comment]
Annotate my 2021  X long range plus raven doesn’t have it, but my 2021 model Y standard range does… same hardware same software iteration
