### ISSUE TITLE
Ramping not working as designed

### ISSUE THREAD

**Issue by ThatsG00d** [teslamotors/light-show#53]
I have 2022 MYLR (reflector lights). if I understand doc correctly then outer and inner beam lights, channel 4 (5, 6), signature, and front turn signals support ramping.
I created a lightshow and ramping up front turn signals (ON command with 80% brightness for ramping up in 1,000 ms) works like a charm.
A ramp down (ON command with 10% brightness for turning on at max brightness and then ramping down in 500 ms) doesn't do anything for outer/inner beams. channel 4, nor signature.
Am I missing something?

**Comment by spaceXrace** [comment]
They have to be manually set to 100% brightness before they can be ramped off. Make sure the 100% effect is at least 3 frames long, anything shorter than that won't always activate.

Also, 2022 MYLR is very likely to have the Matrix Lights, so the outer main beams won't ramp.
