### ISSUE TITLE
Copy/paste getting Graphics error

### ISSUE THREAD

**Issue by Fatso1947** [teslamotors/light-show#55]
![Graphics Driver Problem](https://user-images.githubusercontent.com/24317018/204670886-6a40c217-a5f8-4684-aec6-cecbc1b39c6a.jpg)

I use xLights for Tesla Lightshows.  I am on PC running Windows 11.  My xLights version 2022.23 64 bit

I just started to get this error after the last update.  I do not believe the problem is in my computer nor the graphics card because none of them have changed.  I have frequently used copy/paste on my lightshows in the past with no problems.

I am an applications user, not a coder.  I have no ability to explore the underlying code in xLights.  Any help gratefully appreciated.

**Comment by JVB-Tesla** [comment]
Try the updated project. I expect that'll resolve your issue. If issues persist, I suggest you post your question on the xLights forum.
