### ISSUE TITLE
2022.44.2 MY LR June 22 not working with 64GB exFAT Stick

### ISSUE THREAD

**Issue by Heimdall-One** [teslamotors/light-show#57]
Was this feature with an update?

I used an 64GB Flash Drive freshly formatted in exFAT on Windows and created the LightShow Folder with 2 lightshow files in it. Tried .wav and .mp3 both do not work either. 

Stick was plugged directly into the glovebox USB. Are there any limitations or does the Flash Drive have to be named specifically?

**Comment by Heimdall-One** [comment]
Found an older 16 Gig USB Stick, made it Fat32, does not do the trick either.
![t1](https://user-images.githubusercontent.com/67554653/207446623-170e32b2-3fa7-4d54-9ea0-1dce1628c2ea.png)
![t2](https://user-images.githubusercontent.com/67554653/207446624-b0028445-c7d0-4fe8-9f02-7fb936a2c39c.png)

**Comment by spaceXrace** [comment]
Maybe you have file name extensions hidden, and the actual name of the file is now lightshow.fseq.fseq?

1) Open File Explorer from the taskbar.
2) Select View > Options > Change folder and search options.
3) Select the View tab and, in Advanced settings, select Show hidden files, folders, and drives and OK.

**Comment by Heimdall-One** [comment]
> Maybe you have file name extensions hidden, and the actual name of the file is now lightshow.fseq.fseq?

Unfortunately not. Checked that first :D in a Forum I got the hint, that I should try and format the stick in the car first.
