### ISSUE TITLE
MYP Trunk not opening/closing

### ISSUE THREAD

**Issue by jalexy12** [teslamotors/light-show#6]
I noticed in the default Christmas light show the MYP rear liftgate wasn't opening. I created a custom show as well and the rear liftgate didn't open. 

It seems like it's unlocking (?) -- you can hear some sort of motor/internal latch unlatching, it just doesn't lift.

The rear liftgate opens properly from the app when pressing the external button, etc.

I've changed the lift height previously for the rear liftgate, so wondering if that may have something to do with it.

It definitely has enough clearance as well to perform -- I pulled out from the garage so there was probably at least 7-10ft between the closest obstacle.

**Edit: I reset my trunk to factory default height and it worked again. Maybe a bug?**

**Comment by nelsongraca** [comment]
Mine has a custom height and it works.

**Comment by JVB-Tesla** [comment]
Thanks for the report.
