### ISSUE TITLE
xLights update made model S "vanish"

### ISSUE THREAD

**Issue by ThatsG00d** [teslamotors/light-show#61]
in a moment of weakness I gave in when the software nagged me to update.
xLights updated to 2022.24 and now the model S is not there anymore.
I copied the tesla_xlights_show_folder again but that didn't fix it.
I followed the "Getting started with the Tesla xLights project directory" instructions as I did when I first got the software almost a year ago but now I can't get the car model back.

Any help is greatly appreciated.

**Comment by bcarriveau** [comment]
Can you add any of the built in models or lines or.do they all dissapear? If not Update video drivers, if that doesn't fix it try changing xlights openGl version from auto to 3x.

**Comment by ThatsG00d** [comment]
Solved - I completely uninstalled xLights and started from scratch installing 2022.24 again.
Then copying the content of the zip folder again and making the configuration changes/adjustments in the software.
took a moment while the software appeared unresponsive but now the Tesla MS is back and I am back in "business".
I am not sure what it was but now it works again and I can work on "Santa is coming to town" light show just in time.
