### ISSUE TITLE
Bug: Keyframe Marker jumps in Exponential Steps

### ISSUE THREAD

**Issue by KarlMags** [teslamotors/light-show#70]
Expected Behavior:
When trying to set a marker in the sequencer, the marker is supposed to be set where I click in the music timeline at the top:
![image](https://user-images.githubusercontent.com/75528948/236053699-18bd21f8-228c-46a8-88b5-bd3931003460.png)

Actual behavior:
The further you move along the timeline, the further away the marker jumps at an exponential rate.
The fine blue mark showing where I clicked in the timeline, and the green > showing where the marker was set.

![image](https://user-images.githubusercontent.com/75528948/236053937-bd167fdd-11b9-4b98-a0a8-0fddaf3ab8c6.png)
![image](https://user-images.githubusercontent.com/75528948/236053972-2e70436d-e952-420e-9815-2a0c857fead4.png)
![image](https://user-images.githubusercontent.com/75528948/236054010-749348d6-9ae0-494d-982c-2f00944f48ba.png)

At just 2.8sec, it's already outside the viewport.

Steps for Reproduction:

1. Create a new sequence
2. Go to Sequncer
3. Click at the beginning of the timeline
4. Click at another second
5. Click at another second
6. Notice the marker jumping further away with each step.

UX Value:
- Severe
- Makes the application a pain in the ass to use

**Comment by xingxu21** [comment]
I hate writing dismissal comments, but this is a bug with XLight software relevant for their [github issues](https://github.com/smeighan/xLights/issues) per their "where to report a bug" [FAQ](https://xlights.org/hrf_faq/how-do-i-report-a-problem/) not with Tesla motors light-show repository, so this issue should be closed as irrelevant and redirected to their github

**Comment by JVB-Tesla** [comment]
Thanks for commenting @xingxu21 . Closing.
