### ISSUE TITLE
This light show will be limited on vehicle software versions less than 2022.44.25

### ISSUE THREAD

**Issue by kwezem** [teslamotors/light-show#71]
Hello ! I don't understand why i hace this message ?

![image](https://user-images.githubusercontent.com/79536250/236646375-e49f377e-7cb3-4c33-b7f1-156fa63bdcb8.png)

Have a good day

**Comment by JVB-Tesla** [comment]
This online validator you screenshotted is not created or maintained by Tesla.

However, I expect this means your light show is longer than can be played on vehicles with vehicle software older than 2022.44.25.

If you vehicle has updated in the last 6 months, this won't be an issue.
